### ISSUE TITLE
Cevap olarak yazıyorum

### ISSUE THREAD

**Issue by fahrettinenes** [cemahseri/FileEraser#2]
Öncelikle haline gerçekten acıyorum, tam olarak neyden bahsettiğimi bile anlamamışsın ki cevap veriyorsun :D Burada bahsettiğim şey; `if` bloklarında eğer ki tek satır bulunuyorsa süslü parantez kullanmana gerek yok, ben de buna uyulmadığı zaman şahsen rahatsız olurum ve gözlerim kanar. Yalnızca **gözlerimin kanadığını** belirttim, ancak bu kadar kuduracağını bilsem hiç mesaj bile yazmazdım 😂

**Comment by cemahseri** [comment]
Daha Issues kısmının ne için kullanıldığını bilmiyorsun ve gelmiş hâlâ burada tatava yapıp haline acıyorum diyorsun. Fazlasıyla ironik. Bir açıklama yapacağın zaman noktalı virgül değil, iki nokta kullanırsın. Türkçeye hakim olduğunu sanman ve böylesine basit bir hata yapman gerçekten komik.

Bahsettiğin şey StyleCop'un [SA1503](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1503.md) CheckId'li layout kuralını ihlal ediyor. Keşke -kullandığın dili tasarlayan firmanın önerdiği kodlama stili başta olmak üzere- stiller hakkında bilgin olsaydı da böylesine komik bir duruma düşmeseydin. Sana üzücü bir haberim var fakat ne yazık ki senin boktan fikrin ve rahatın kimsenin umurunda değil maalesef. Uygulama ile alakalı bir sorun varsa buraya sorun oluşturursun ve durumu açıklarsın. Burası gelip ağlayabileceğin bir duvar değil maalesef. Eğer bu tarz negatif IQ hareketlere devam edersem sevinerek engellemek zorunda kalacağım.
